### PR TITLE
Update @vue/language-server to 2.0.19, use @vue/typescript-plugin

### PR DESCRIPTION
**Pull request by zulus**
* Update @vue components
* Remove second vue LS instance
* Implement TypeScriptPlugin languages section
* Bind *.vue files to typescript lsp

Due https://github.com/vuejs/language-tools/issues/4246 I had to disable typescript-plugin-css-modules and typescript-lit-html-plugin

### CODE REVIEW

**Comment by akurtakov** [comment]
So is this one "blocked" ?

**Comment by akurtakov** [comment]
@zulus Do you think you'll find time to finish this one?

**Comment by zulus** [comment]
Can be merged after license clear, editor haven't valid syntax highlighting, but this is tm4e bug

**Comment by akurtakov** [comment]
Please remove the do not merge part and push yourself when ready.

**Comment by akurtakov** [comment]
Licensecheck succeeded now but there are a bunch of extra failures that do not fail on master .

**Comment by zulus** [comment]
> Licensecheck succeeded now but there are a bunch of extra failures that do not fail on master .

I forgot commit plugin re-enable, checking in progress

**Comment by zulus** [comment]
> > Licensecheck succeeded now but there are a bunch of extra failures that do not fail on master .
> 
> xD, looks like latest typescript follows LSP protocol, and produce diagnostics only if client inform about publicDiagnostics capability, LSP4E never send this information ;) another blocker...

https://github.com/eclipse/lsp4e/issues/1007

**Comment by mickaelistria** [comment]
It seems like the issue are the same one as in https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/pull/1459 , which seems to be a blocker then.

**Comment by akurtakov** [comment]
@zulus Thanks for figuring this one and fixing lsp4e!

**Comment by mickaelistria** [comment]
> Thanks for figuring this one and fixing lsp4e!

I strongly support that, you've manage to unblock a long standing chain of actions here; thank you!

**Comment by zulus** [comment]
Fortunately I have a lot of time now ;)

**Pull request merged**
