### PR TITLE
Use vscode-js-debug in place of deprecated node-debug2

### PR DESCRIPTION
**Pull request by mickaelistria**
This was drafted while working on `startDebugging` support for LSP4E.
Before we can merge in Wild Web Developer, this requires the following issues to be fixed 
- https://github.com/eclipse-lsp4j/lsp4j/issues/721 (and LSP4J released)
- LSP4E released
- a strategy to get dapDebugAdapter inside node_modules (rather than reference a local copy)

### CODE REVIEW

**Comment by mickaelistria** [comment]
See https://github.com/microsoft/vscode-js-debug/issues/926#issuecomment-1741635736 about getting dapDebugAdapter conveniently.

**Comment by mickaelistria** [comment]
IP review submitted: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10778

**Comment by mickaelistria** [comment]
Moving back to draft as there are still 2 important limitations:
* The output is not printed in internal console
* Run mode doesn't seem to work (debug does)

**Comment by zulus** [comment]
In theory this also replace deprecated chrome debug adapter (pwa-chrome) and supports edge (pwa-msedge, windows only)

**Comment by mickaelistria** [comment]
Both issues listed are fixed in LSP4E DAP support, but there is another issue that now `getThreads()` doesn't return (request stuck) when the thread isn't suspended. This does cause multiple issues in LSP4E DAP support. I'm investigating fixing it there.

**Comment by mickaelistria** [comment]
At the moment, I didn't manage to get a TypeScript program being debugged...

**Comment by mickaelistria** [comment]
Submitted question to https://github.com/microsoft/vscode-js-debug/issues/1838

**Comment by wesleybl** [comment]
@mickaelistria I installed the latest snapshot and I'm not able to debug js files with this new debug. I created a simple js file, right clicked on the file and selected `Run As -> Node Program`. Then I get an error window with the message:

```
An internal error occurred during: "Launching New_configuration".
java.net.ConnectException: Connection refused
```

The console prints the message:

```
Debug server listening at 127.0.0.1:46831
```

How do I debug?

**Comment by mickaelistria** [comment]
Can you please open a new issue about this and share the content of workspace/.metadata/.log ?

**Pull request merged**
