### PR TITLE
Update XML and XSL grammars to the latest ones from VSCode 1.78.0

### PR DESCRIPTION
**Pull request by vrubezhny**

### CODE REVIEW

**Comment by akurtakov** [comment]
@vrubezhny what is the status of this one?

**Comment by vrubezhny** [comment]
These grammars appear to be erroneous - see https://github.com/eclipse/tm4e/issues/545 - so the PR is not to be merged.

Should be replaced either by fixed grammars from newer vscode version or by switching to use the grammars provided by  TM4E Language Pack.

**Comment by akurtakov** [comment]
No longer needed as xml and xsl grammars/language-configs are used from tm4e via https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/commit/decec1b7eb6b06808ae0edede700238c1c45df0d and https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/commit/ff48fba15f8f97cddfaca5c0da0fd194373d7380

**Pull request closed without merging**
