### PR TITLE
References to third-party repositories removed

### PR DESCRIPTION
**Pull request by OLibutzki**

### CODE REVIEW

**Comment by mickaelistria** [comment]
We can merge it as soon as build is fine and the output p2 repo is verified (the repo is accessible through Jenkins after build completion)
But at the moment, it looks like the build is failing.

**Comment by OLibutzki** [comment]
> But at the moment, it looks like the build is failing.

I can confirm that. Maybe this is caused by the target platform which uses https://download.eclipse.org/releases/latest/. Looks like `org.eclipse.mylyn.wikitext_feature.feature.group` is not part of the repo anymore.

That issue seems not to be related to this PR.

**Comment by mickaelistria** [comment]
OK, can you please fix the dependency issue by the way?

**Comment by OLibutzki** [comment]
> OK, can you please fix the dependency issue by the way?

The feature seems to be renamed:
`org.eclipse.mylyn.wikitext_feature` --> `org.eclipse.mylyn.wikitext.feature`

I don't know what to do with `org.eclipse.mylyn.wikitext.editors_feature` hwich is used in `epp.product`. It seems not to exist anymore.

**Comment by OLibutzki** [comment]
> I don't know what to do with org.eclipse.mylyn.wikitext.editors_feature which is used in epp.product. It seems not to exist anymore.

I fixed it by using `org.eclipse.mylyn.wikitext.feature`.

**Comment by OLibutzki** [comment]
Build is successful, but the p2 repo is huge as all the features/plugins of the previously referenced repositories are packaged in it: https://ci.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/PR-1491/lastSuccessfulBuild/artifact/repository/target/repository/

**Comment by mickaelistria** [comment]
Let's just merge it if it fixes many problems.
I think we should just consider removing the product. This was a replacement for the former "Eclipse IDE for Web and JavaScript developers" package in EPP, but realistically, I don't think it's useful to anyone and I'm certain Victor or myself at least wouldn't mind dropping it.

**Pull request merged**
