### PR TITLE
XML custom client commands

### PR DESCRIPTION
**Pull request by angelozerr**
This PR provides XML custom client commands for: 

 * execute the LSP serach references when CodeLens (references) is clicked to fix https://github.com/eclipse/wildwebdeveloper/issues/644
 * open uri
 * associate XML with XSD, DTD grammar

### CODE REVIEW

**Comment by angelozerr** [comment]
Here a demo with the sample.dtd describes in https://github.com/eclipse/wildwebdeveloper/issues/644:

DTDCodeLensReferences

This PR requires the merge of LSP4E PR https://github.com/eclipse/lsp4e/pull/282

**Comment by akurtakov** [comment]
What is the status of this one? If still of interest please finish it.

**Comment by angelozerr** [comment]
@akurtakov I'm sorry I have no time to work again, even if I think it can be a nice feature (that we have in vscode-xml)

**Comment by akurtakov** [comment]
@angelozerr If you don't plan to finish this one please close it.

**Comment by angelozerr** [comment]
Sorry I have no time to work on it.

**Pull request closed without merging**
