### PR TITLE
Preference store per language

### PR DESCRIPTION
**Pull request by angelozerr**
Preference store per language

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR provides the capability to have a preference store per language ID.

This PR is very important (please merge it before the release) to support in the future spacesForTab preferences per language.

**Comment by angelozerr** [comment]
This PR doesn't work -( since it seems that we can have a preference store per plugin. It is really annoying.

**Comment by mickaelistria** [comment]
> This PR doesn't work -( since it seems that we can have a preference store per plugin. It is really annoying.

Do you mean that the current code ignores the store, fails at creating it, or throws other errors...?
If this helps, you may consider creating another scope dedicated to Wild Web Developer prefs.

**Comment by mickaelistria** [comment]
One possibility would be to create some kind of SubPreferenceStore that would allow to use a single store, but have a projection and subset of it. So when asking for preference `tabsWidth`, such SubPreferenceStore would actually request `languageServerId/tabWith` on the preferenceStore of org.eclipse.wildwebdeveloper.

**Comment by angelozerr** [comment]
@mickaelistria we need to use `spacesForTab` and not `languageServerId/tabWith` as key, because this settings should be used:

 * by LSP4E for formatting
 * by the editor when user will press on `Tab`, it should generate some spaces (if spacesForTab is enabled)
 * by TM4E with onEnterRules

For the 2 last usecase, `languageServerId/tabWith` is unkwown.

I can manage those all usecases with https://github.com/eclipse-platform/eclipse.platform.text/pull/109

**Comment by akurtakov** [comment]
What is the status of this one? PRs lurking around are generally not helpful if no one plans to work on them.

**Comment by angelozerr** [comment]
Sorry I have no time to work on it.

**Pull request closed without merging**
