### PR TITLE
Update VSCode (v.1.89.0) extensions

### PR DESCRIPTION
**Pull request by vrubezhny**
Release notes: https://github.com/microsoft/vscode/releases/tag/1.89.0

### CODE REVIEW

**Comment by vrubezhny** [comment]
An IP Team review request is created: [-/-/vscode/language-features-subset/1.88.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14575)

**Comment by akurtakov** [comment]
VScode cq is approved.

**Comment by mickaelistria** [comment]
A version bump is necessary.

**Comment by mickaelistria** [comment]
IP issue for sass is https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14631

**Comment by vrubezhny** [comment]
The IPTeam Review request is successfully resolved for vscode 1.89.0.

**Pull request merged**
