### PR TITLE
Fix #1247 - Maven build use node from PATH on mac os

### LINKED ISSUE #1247: Maven build use node from PATH on mac os
For now this code always return true on MAC: https://github.com/eclipse/wildwebdeveloper/blob/e52e0990f609f3dcbac5648a4bd012ecf9d753a5

Due this process builder always receiving NPM absolute path only, so use node from PATH (if exists) or fail (`/bin/env node`)

I think line from above should be just dropped, npm should always be prefixed by built-in node (if exists)

### PR DESCRIPTION
**Pull request by zulus**
Introduce NodeJSManager helpers to always produce ProcessBuilder with commands:

node_executable npm_location rest commands

these command is also used in NpmLaunchDelegate!

### CODE REVIEW

**Comment by vrubezhny** [comment]
@zulus I don't get how does it help to use embedded Node.js instead of a version that is found and used when `npm` (or `NPM.CMD`) is executed with 
```
#!/usr/bin/env node
````

**Comment by zulus** [comment]
> @zulus I don't get how does it help to use embedded Node.js instead of a version that is found and used when `npm` (or `NPM.CMD`) is executed with
> 
> ```
> #!/usr/bin/env node
> ```

Because rather than just run:
`$: npm install something`

Based on executable location search for  `cli.js` (or `npm-cli.js`) and execute:

`$ path_to_npm_builtin_or_from_property path_to_cli.js install something`

**Comment by zulus** [comment]
Just check console log for tests (MacOS, Windows, Linux)

**Comment by vrubezhny** [comment]
Won't this `path_to_cli.js`  still be executed with `#!/usr/bin/env node`?

> Just check console log for tests (MacOS, Windows, Linux)

I had Node.js 20 configured for this purpose on MacOS GitHub build action :)

**Comment by zulus** [comment]
After this path no both will be directly from embedder

**Review by vrubezhny — APPROVED** [review]
Looks good to me

**Pull request merged**
