### PR TITLE
Fix #1343 - add fsevents for MacOS users

### LINKED ISSUE #1343: Add fsevents package to node_modules
fsevent is special optional package used by any node-js watcher (for example chokidar) to play with native macosx fs events, because wildwebdeveloper is built on linux machines it isn't part of final node_modules.

Due this LS servers on macos work slower than in vscode (it's pooling based), pom.xml could run `npm pack fsevents` and later unpack it into node_modules

### PR DESCRIPTION
**Pull request by zulus**
Just add to package.json, with force will be installed even on linux/windows

### CODE REVIEW

**Comment by zulus** [comment]
@mickaelistria am I doing something wrong? Looks like my comment with `/request-license-review` has been ignored (In theory I have rights)

**Comment by mickaelistria** [comment]
I don't know. I also faced this issue earlier and I noticed that the GitHub action is marked as skipped ( https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/actions/runs/6300253210 ). I don't know what that means, but I know that's not expected.

**Comment by vrubezhny** [comment]
@zulus After you commented with `/request-license-review` the following IP Team Review request was created: [npm/npmjs/@babel/parser/7.23.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10663).
Then it takes some time for the request to be resolved (sometimes it takes days due to the need to be manually resolved). 
After the review request is resolved as `Approved` the `License check / npm-check` build job is to be re-run manually - if no other NPM Modules require an update then it should be built with success.

**Comment by zulus** [comment]
> I don't know. I also faced this issue earlier and I noticed that the GitHub action is marked as skipped ( https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/actions/runs/6300253210 ). I don't know what that means, but I know that's not expected.

Based on workflow definition is ok. These jobs skip if PR was just commented with '/request-license-review'

> @zulus After you commented with `/request-license-review` the following IP Team Review request was created: [npm/npmjs/@babel/parser/7.23.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10663). Then it takes some time for the request to be resolved (sometimes it takes days due to the need to be manually resolved). After the review request is resolved as `Approved` the `License check / npm-check` build job is to be re-run manually - if no other NPM Modules require a review (as some modules might be updated on every build) then it should be built with success.

Thank You, previously I saw auto rocket emoji. Looks like I have to manually check gitlab and search for libraries

**Review by vrubezhny — APPROVED** [review]
Looks good to me.

@zulus Thanks for the improvement! 

It'd be good to mention somehow this change in README or CONTRIBUTION - I don't know where exactly - why do we need this NPM Dependency to be included?  
(Usually we do not keep not used dependencies with no reason, so someone, who doesn't know why this one is added, might suggest removing it. So it'd better to be documented somehow)

**Comment by zulus** [comment]
The IP Team Review requests are created regarding the proposal:

* [npm/npmjs/@babel/parser/7.23.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10663)

**Comment by vrubezhny** [comment]
> Thank You, previously I saw auto rocket emoji. Looks like I have to manually check gitlab and search for libraries

Sometimes it takes quite a long time for dependencies to be approved by IP Team, so we didn't ever think on adding some automation here.

You can skip visiting the https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/?sort=created_date&state=closed&author_username=wildwebdeveloper-bot&first_page_size=100 - Just re-run `npm-check` job in few minutes after you did `/request-license-review` - normally it takes 10-30 minutes for a dependency to be approved if no IP Team manual intervention is required depending on the workload of the IP Team's bot.

**Comment by zulus** [comment]
> Looks good to me.
> 
> @zulus Thanks for the improvement!
> 
> It'd be good to mention somehow this change in README or CONTRIBUTION - I don't know where exactly - why do we need this NPM Dependency to be included? (Usually we do not keep not used dependencies with no reason, so someone, who doesn't know why this one is added, might suggest removing it. So it'd better to be documented somehow)

this is not relared to fsevents, error win npm I also saw in my other PR. One of the packages have relaxed dependencies. I'll check which one

**Comment by mickaelistria** [comment]
@vrubezhny I think something regressed in the license-check. It used to react and mention the opened IP reviews if any. I don't see this now...

**Comment by vrubezhny** [comment]
> @vrubezhny I think something regressed in the license-check. It used to react and mention the opened IP reviews if any. I don't see this now...

Some time ago I reported an issue to license check - it was creating a duplicating review requests for the same NPM dependency after the first one is already created and continuing  repeatedly run the check with `-review` argument - probably it is fixed now and the repeated executions of `/request-license-review` get canceled or something like this.

**Comment by zulus** [comment]
> It'd be good to mention somehow this change in README or CONTRIBUTION - I don't know where exactly - why do we need this NPM Dependency to be included? (Usually we do not keep not used dependencies with no reason, so someone, who doesn't know why this one is added, might suggest removing it. So it'd better to be documented somehow)

`@vue/compiler-core` (one of vue ls deps) have dependency to ` "@babel/parser" : "^7.21.3"` this is why license warning appear, they recently published new version

**Pull request merged**
